on:
  push:
    # https://docs.github.com/en/webhooks-and-events/events/github-event-types#event-payload-object-for-pushevent
    # https://stackoverflow.com/a/69919067
    tags:
      - "v*"

env:
  NODE_VERSION: 18
jobs:
  gen_change_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: last-release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        continue-on-error: true
        with:
          owner: aaronclong
          repo: barcode-detector-polyfill
          excludes: prerelease, draft

      - name:
        if: steps.last-release.outcome != 'failure'
        run: |
          echo "LAST_RELEASE_TAG=${{steps.last-release.outputs.release}}" >> $GITHUB_ENV

      - name:
        if: steps.last-release.outcome == 'failure'
        run: |
          echo "LAST_RELEASE_TAG=v0.0.0" >> $GITHUB_ENV

      - name: "Build Changelog"
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          base-ref: ${{ env.LAST_RELEASE_TAG }}
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the changelog
        run: |
          frag=$(cat <<EOF
           ${{ steps.changelog.outputs.changelog }}
          EOF)
          echo "$frag" >> CHANGE_LOG_FRAG.md

      - name: Archive CHANGE_LOG_FRAG
        uses: actions/upload-artifact@v3
        with:
          name: change-log-frag
          path: "CHANGE_LOG_FRAG.md"

  build_library:
    needs: gen_change_log
    uses: ./.github/workflows/build-library.yml

  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [gen_change_log, build_library]
    steps:
      - name: Create artifacts folder
        run: mkdir -p artifacts
        shell: bash

      - uses: actions/download-artifact@v3
        id: download
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: artifacts/change-log-frag/CHANGE_LOG_FRAG.md
          files: |
            artifacts/library-build-dist/*

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Publish to NPM
        shell: bash
        run: |
          version=$(echo "${{github.ref}}" | sed 's/v//g'
          echo "This the version ${version}"
          npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish artifacts/library-build-dist/aaronclong-barcode-detection-polyfill-${version}.tgz
